<a href="https://colab.research.google.com/github/noralkhalil/Pytorch-Course/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
mytorch = torch.arange(10)
mytorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and View
mytorch = my_torch.reshape (2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Reshape if we dount know the number of items using -1

Spalten:


In [5]:

mytorch2 = torch.arange(10)
mytorch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
mytorch2 = my_torch2.reshape(2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Zeilen:

In [21]:
mytorch3 = torch.arange(10)
mytorch3


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
mytorch3 = my_torch3.reshape(-1,5)
mytorch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# View and Reshape ara similar

In [23]:
mytorch4 = torch.arange(10)
mytorch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
mytorch5 = mytorch4.view(2,5)
mytorch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Change elements/items with Reshape and View

In [33]:
mytorch6 = torch.arange(10)
mytorch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
mytorch7 = mytorch6.reshape(2,5)
mytorch7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [39]:
mytorch6 [1] = 4141 # now i want to change the secound item
mytorch6


tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [40]:
mytorch7 # this has been updated

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])