<a href="https://colab.research.google.com/github/noralkhalil/Pytorch-Course/blob/main/TensorMath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
# import numpy as np


In [3]:
tensorA = torch.tensor([1,2,3,4])
tensorB = torch.tensor([5,6,7,8])


In [4]:
# addition:
tensorA + tensorB

tensor([ 6,  8, 10, 12])

In [5]:
# addition Longhad:
torch.add(tensorA, tensorB)

tensor([ 6,  8, 10, 12])

In [6]:
# Subtraction:
tensorA - tensorB

tensor([-4, -4, -4, -4])

In [7]:
# Sub Function:
torch.sub(tensorA, tensorB)

tensor([-4, -4, -4, -4])

In [8]:
# Multiplication:
tensorA * tensorB

tensor([ 5, 12, 21, 32])

In [9]:
# Mul longhad:
torch.mul(tensorA, tensorB)

tensor([ 5, 12, 21, 32])

In [10]:
# Devision:
tensorA / tensorB

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [11]:
# Div Longhad:
torch.div(tensorA, tensorB)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [12]:
# Remainder Moduls:
tensorB % tensorA

tensor([0, 0, 1, 0])

In [15]:
# Rmeainder Longhad:
torch.remainder(tensorB, tensorA)

tensor([0, 0, 1, 0])

In [17]:
# Exponents / Power
torch.pow(tensorA, tensorB)

tensor([    1,    64,  2187, 65536])

In [18]:
# Another way to wirte longhad
tensorA.add(tensorB)

tensor([ 6,  8, 10, 12])

In [19]:
# Reassignment:
tensorA + tensorB

tensor([ 6,  8, 10, 12])